name: Convert TypeScript to JSON
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  publish_json:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && github.repository == 'subquery/templates'"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build and Deploy
        run: npm run build && npm run start
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '[SKIP CI] update output'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
